# Clear cache command: php bin/console cache:clear
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

logout:
    path: /logout
    methods: GET

login:
    path: /connection
    methods: GET