# Clear cache command: C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\php.exe bin/console cache:clear
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\DefaultController::index

maintenance:
    path: /maintenance
    controller: App\Controller\DefaultController::maintenance

booking:
    path: /booking
    controller: App\Controller\BookingController::booking

galery:
    path: /galery
    controller: App\Controller\GaleryController::galery

connection:
    path: /connection
    controller: App\Controller\ConnectionController::connection

register:
    path: /register
    controller: App\Controller\RegisterController::register

galeryManager:
    path: panel/galeryManager
    controller: App\Controller\Admin\GaleryManagerController::galeryManager

shedulerManager:
    path: panel/shedulerManager
    controller: App\Controller\Admin\ShedulerManagerController::shedulerManager

bookingManager:
    path: panel/bookingManager
    controller: App\Controller\Admin\BookingManagerController::bookingManager

cardManager:
    path: panel/cardManager
    controller: App\Controller\Admin\CardManagerController::cardManager

panel:
    path: /panel
    controller: App\Controller\ConnectionController::connection