controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\DefaultController::index

booking:
    path: /booking
    controller: App\Controller\BookingController::booking

galery:
    path: /galery
    controller: App\Controller\GaleryController::galery

connection:
    path: /connection
    controller: App\Controller\ConnectionController::connection

register:
    path: /register
    controller: App\Controller\RegisterController::register